"""Artifact 5's endpoint, pinned. Any change ends the experiment rather than
continuing across it (docs/experiment-a5.md). Generated by scripts/a5_pins.py
from endpoint 2ilkjkm9ob4qvo."""

PINNED = {'flashboot': False,
 'gpuTypeIds': ['NVIDIA GeForce RTX 4090'],
 'networkVolumeId': '9c7ut2slrd',
 'templateId': 'fszq9rhod3',
 'workersMin': 0}
