"""The gate on the arrivals the engine received (amendment 2026-10-05, third)."""

import random

import pytest

from autoscale.service import ServiceCurve
from autoscale.sim import run_fixed_capacity
from autoscale.validation import (
    REPEATS,
    EngineRun,
    RealRun,
    engine_trajectories,
    validate,
    validate_engine_arrivals,
)

CURVE = ServiceCurve(points=[(0, 0.2, 0.0, 0.0), (1, 0.2, 50.0, 1.0), (8, 0.4, 300.0, 1.0)],
                     measured=True)
UNTIL = 200.0


def _schedule(seed=3, rate=12.0, until=170.0):
    rng = random.Random(seed)
    t, out = 0.0, []
    while True:
        t += rng.expovariate(rate)
        if t > until:
            return out
        out.append(t)


def test_arrivals_are_aligned_on_the_least_delayed_request():
    run = EngineRun(sent=(1.0, 2.0, 3.0), received=(1000.5, 1003.0, None),
                    latencies=(0.2, 0.3, None), replicas=1, until=10.0, host_ids=("w",))
    arrivals, latencies = run.engine_arrivals()
    # offset = min(999.5, 1001.0) = 999.5: request 0 arrives at its send time
    assert arrivals == pytest.approx([1.0, 3.5]) and latencies == (0.2, 0.3)
    assert run.never_reached() == (2,)


def test_a_request_finishing_after_the_window_is_unfinished():
    run = EngineRun(sent=(1.0, 9.0), received=(101.0, 109.5), latencies=(0.2, 0.8),
                    replicas=1, until=10.0, host_ids=("w",))
    arrivals, latencies = run.engine_arrivals()
    assert arrivals == pytest.approx([1.0, 9.5]) and latencies == (0.2, None)


def test_malformed_runs_are_refused():
    base = {"sent": (1.0,), "received": (5.0,), "latencies": (0.2,), "replicas": 1,
            "until": 10.0, "host_ids": ("w",)}
    with pytest.raises(ValueError, match="one entry per request"):
        EngineRun(**{**base, "received": (5.0, 6.0)})
    with pytest.raises(ValueError, match="no request reached"):
        EngineRun(**{**base, "received": (None,), "latencies": (None,)})
    with pytest.raises(ValueError, match="host"):
        EngineRun(**{**base, "host_ids": ()})
    with pytest.raises(ValueError, match="window"):
        EngineRun(sent=(1.0, 2.0), received=(5.0, 50.0), latencies=(0.1, 0.1), replicas=1,
                  until=10.0, host_ids=("w",)).engine_arrivals()


def _faithful_runs(schedule, latency_noise):
    """Runs whose engine arrivals ARE the schedule (no load-balancer delay)."""
    sim = run_fixed_capacity(list(schedule), 1, CURVE, UNTIL)
    by_arrival = dict(sim.completed_requests())
    runs = []
    for k, noise in enumerate(latency_noise):
        lat = tuple(by_arrival[t] + noise for t in schedule)
        runs.append((tuple(schedule), lat, k))
    return runs


def test_without_delays_it_gives_the_signed_gates_verdict():
    schedule = _schedule()
    triples = _faithful_runs(schedule, (0.004, -0.003, 0.010))
    engine = [EngineRun(sent=s, received=tuple(t + 1000.0 for t in s), latencies=lat,
                        replicas=1, until=UNTIL, host_ids=(f"w{k}",)) for s, lat, k in triples]
    signed = [RealRun(schedule=s, sent=s, latencies=lat, replicas=1, until=UNTIL,
                      host_ids=(f"w{k}",)) for s, lat, k in triples]
    assert validate_engine_arrivals(engine, CURVE) == validate(signed, CURVE)


def test_each_repeat_is_predicted_from_its_own_arrivals():
    """A stall delays a burst at the engine. Real latencies generated by the
    model from those arrivals agree with the model; scored against the
    schedule's prediction they would not have to."""
    schedule = _schedule()
    runs = []
    for k, stall_at in enumerate((40.0, 90.0, 130.0)):
        received = [t if not (stall_at <= t < stall_at + 3.0) else stall_at + 3.0
                    for t in schedule]
        order = sorted(range(len(received)), key=lambda i: received[i])
        sim = run_fixed_capacity(sorted(received), 1, CURVE, UNTIL)
        done = sorted(sim.completed_requests(), key=lambda pair: pair[0])
        lat = [None] * len(schedule)
        for i, (_, latency) in zip(order, done, strict=False):
            lat[i] = latency
        runs.append(EngineRun(sent=tuple(schedule), received=tuple(r + 500.0 for r in received),
                              latencies=tuple(lat), replicas=1, until=UNTIL,
                              host_ids=(f"w{k}",)))
    result = validate_engine_arrivals(runs, CURVE)
    assert result.outcome == "passed" and result.misses == 0
    real, pred = engine_trajectories(runs[0], CURVE)
    # Equal up to the float residue of putting the engine clock on the run's timeline.
    assert [b.p50 for b in real] == pytest.approx([b.p50 for b in pred], abs=1e-9)


def test_the_repeat_count_and_one_window_are_enforced():
    schedule = _schedule()
    triples = _faithful_runs(schedule, (0.0,) * REPEATS)
    runs = [EngineRun(sent=s, received=s, latencies=lat, replicas=1, until=UNTIL,
                      host_ids=("w",)) for s, lat, _ in triples]
    with pytest.raises(ValueError, match="exactly"):
        validate_engine_arrivals(runs[:2], CURVE)
    other = EngineRun(sent=runs[0].sent, received=runs[0].received, latencies=runs[0].latencies,
                      replicas=1, until=UNTIL - 10.0, host_ids=("w",))
    with pytest.raises(ValueError, match="window"):
        validate_engine_arrivals([runs[0], runs[1], other], CURVE)
