"""Pre-registration step 2, part 2: the values, committed 2026-10-05,
before the first measurement run.

Generated by scripts/a4_step2.py from fixtures/a4/recon-report.json and
data/a4/screen.json under the rules in placement/step2.py. Literals only.
tests/test_placement_registered.py re-derives every value from those inputs
and fails on any difference."""

MODEL = 'Qwen/Qwen3-1.7B'
INPUT_LEN = 1792
OUTPUT_LEN = 256
KV_SPLIT_TOKENS = 55104
KV_SOLO_TOKENS = 168464
SPLIT_CEILING = 26
SOLO_CEILING = 82
OWN_LEVELS = (1, 2, 4, 8, 16, 32, 64)
NEIGHBOUR_LEVELS = (0, 16, 32, 64)
SOLO_LEVELS = (1, 2, 4, 8, 16, 32, 64, 128)
HELD_OUT = ('pair:o24:n48', 'pair:o48:n24')
COMPILE_SHARED = True
EVICTION_WORKS = False
SLEEP_MEASURED = True
VALIDATION_SET = ('Qwen/Qwen3-1.7B', 'Qwen/Qwen3-1.7B', 'Qwen/Qwen3-1.7B')
SWAP_PAIRS = (('Qwen/Qwen3-1.7B', 'Qwen/Qwen3-1.7B'),)
SWAP_COLD_STATES = (False,)
SWAP_REPEATS = 16
OFFERED_GPUS = 1.0
SLO_SWAP_MULTIPLE = 2.0
GPU_HOURLY_RATE = 1.1095
RATE_PROVENANCE = ("derived from RunPod's billing API for endpoint nnypnh9drkq5ux (GET /v1/billing/endpoints: "
 '$0.2443519 for 792.879 s billed, $0.000308 per second), read 2026-10-05')
