"""Pre-registration step 2, part 2: the values, rendered from the rules.

`placement.step2` fixes the rules. Once reconnaissance's report and the
screen's choice exist, `scripts/a4_step2.py` applies the rules and writes
three things from the one set of values this module computes:

- `placement/registered.py`, the values as literals, so a reader sees every
  one without running anything;
- `data/a4/designs/*.json`, the campaign designs `scripts/a4_measure.py` reads;
- the "Step 2, part 2" section of `docs/experiment-a4.md`.

`mismatches` re-derives the values and names every difference, so
`tests/test_placement_registered.py` fails if any of the three drifts from the
rules applied to the committed inputs.
"""

import dataclasses
import math
import pprint

__all__ = ["design_files", "mismatches", "render_doc", "render_module", "values"]

SECTION = "## Step 2, part 2 — values, fixed before the first measurement run"


def values(measurement: dict, screen: dict, *, rate: float, provenance: str) -> dict:
    if not math.isfinite(rate) or rate <= 0:
        raise ValueError(f"the GPU hourly rate must be finite and positive, got {rate!r}")
    if not provenance.strip():
        raise ValueError("the rate needs its provenance: where and when it was read")
    shape = measurement["shape"]
    swaps = measurement["swaps"]
    chosen = screen["chosen"]
    return {
        "MODEL": measurement["model"],
        "INPUT_LEN": shape["input_len"],
        "OUTPUT_LEN": shape["output_len"],
        "KV_SPLIT_TOKENS": measurement["kv_split_tokens"],
        "KV_SOLO_TOKENS": measurement["kv_solo_tokens"],
        "SPLIT_CEILING": shape["split_ceiling"],
        "SOLO_CEILING": measurement["solo_ceiling"],
        "OWN_LEVELS": tuple(measurement["own_levels"]),
        "NEIGHBOUR_LEVELS": tuple(measurement["neighbour_levels"]),
        "SOLO_LEVELS": tuple(measurement["solo_levels"]),
        "HELD_OUT": tuple(measurement["held_out"]),
        "COMPILE_SHARED": measurement["compile_shared"],
        "EVICTION_WORKS": measurement["eviction_works"],
        "SLEEP_MEASURED": measurement["sleep"] is not None,
        "VALIDATION_SET": tuple(measurement["validation_set"]),
        "SWAP_PAIRS": tuple(tuple(p) for p in swaps.pairs),
        "SWAP_COLD_STATES": tuple(swaps.cold_states),
        "SWAP_REPEATS": swaps.repeats,
        "OFFERED_GPUS": chosen["offered_gpus"],
        "SLO_SWAP_MULTIPLE": chosen["slo_swap_multiple"],
        "GPU_HOURLY_RATE": rate,
        "RATE_PROVENANCE": provenance,
    }


def render_module(v: dict, date: str) -> str:
    lines = [
        '"""Pre-registration step 2, part 2: the values, committed ' + date + ",",
        "before the first measurement run.",
        "",
        "Generated by scripts/a4_step2.py from fixtures/a4/recon-report.json and",
        "data/a4/screen.json under the rules in placement/step2.py. Literals only.",
        "tests/test_placement_registered.py re-derives every value from those inputs",
        'and fails on any difference."""',
        "",
    ]
    # pformat wraps long tuples across lines; its output is still a literal.
    lines += [f"{name} = {pprint.pformat(value, width=96)}" for name, value in v.items()]
    return "\n".join(lines) + "\n"


def _solo(v: dict) -> str:
    if v["KV_SOLO_TOKENS"] is None:
        return "not measured by reconnaissance, so the solo grid spans the full range"
    return f"`{v['KV_SOLO_TOKENS']:,}` tokens, ceiling `{v['SOLO_CEILING']}`"


def render_doc(v: dict, date: str) -> str:
    pairs = ", ".join(f"{a} to {b}" for a, b in v["SWAP_PAIRS"])
    states = " and ".join("cold" if c else "warm" for c in v["SWAP_COLD_STATES"])
    return "\n".join([
        SECTION,
        "",
        f"Committed {date}. Every value below is the rules of part 1 applied to",
        "`fixtures/a4/recon-report.json` and `data/a4/screen.json`;",
        "`placement/registered.py` holds them as code, and",
        "`tests/test_placement_registered.py` re-derives them.",
        "",
        f"- **Model class:** `{v['MODEL']}`.",
        f"- **Request shape:** `{v['INPUT_LEN']}` input and `{v['OUTPUT_LEN']}` output tokens.",
        (f"- **KV capacity:** split `{v['KV_SPLIT_TOKENS']:,}` tokens, ceiling "
         f"`{v['SPLIT_CEILING']}` requests; solo {_solo(v)}."),
        (f"- **Co-located grid:** own levels `{v['OWN_LEVELS']}`, neighbour levels "
         f"`{v['NEIGHBOUR_LEVELS']}`; held-out cells `{v['HELD_OUT']}`."),
        f"- **Solo grid:** `{v['SOLO_LEVELS']}`.",
        f"- **Compile cache shared across the 4B checkpoints:** `{v['COMPILE_SHARED']}`.",
        f"- **Page-cache eviction works:** `{v['EVICTION_WORKS']}`; swaps measured {states}.",
        f"- **Sleep-mode arm measured:** `{v['SLEEP_MEASURED']}`.",
        f"- **Validation set:** `{v['VALIDATION_SET']}`.",
        f"- **Swap campaign:** {pairs}; `{v['SWAP_REPEATS']}` repeats per pair and state.",
        (f"- **Screen's choice:** offered load `{v['OFFERED_GPUS']}` GPUs of saturation; SLO "
         f"`{v['SLO_SWAP_MULTIPLE']}` times the simulated swap's median."),
        (f"- **GPU hourly rate:** `{v['GPU_HOURLY_RATE']}` dollars, {v['RATE_PROVENANCE']}. "
         "Artifact 5 reads the same rate from here."),
        "",
    ])


def design_files(measurement: dict) -> dict[str, dict]:
    """The campaign designs as the JSON `scripts/a4_measure.py --design` reads."""
    out = {"cells": dataclasses.asdict(measurement["cells"]),
           "swaps": dataclasses.asdict(measurement["swaps"])}
    if measurement["sleep"] is not None:
        out["sleep"] = dataclasses.asdict(measurement["sleep"])
    return out


def mismatches(registered: dict, expected: dict) -> list[str]:
    """Every name whose committed value differs from the re-derived one, or is
    missing from either side."""
    names = sorted(set(registered) | set(expected))
    return [f"{n}: registered {registered.get(n)!r}, rules give {expected.get(n)!r}"
            for n in names if registered.get(n) != expected.get(n)]
