"""Print multilora/pins.py for the live endpoint.

    set -a; . ./.env; set +a
    .venv/bin/python scripts/a5_pins.py > multilora/pins.py

Refuses an endpoint with FlashBoot on or a warm worker kept (multilora.cli).
"""

import pprint
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from harness.runpod.preflight import fetch_endpoint
from multilora.cli import pins_from_endpoint, require_credentials

TEMPLATE = '''"""Artifact 5's endpoint, pinned. Any change ends the experiment rather than
continuing across it (docs/experiment-a5.md). Generated by scripts/a5_pins.py
from endpoint {endpoint_id}."""

PINNED = {pins}
'''


def main() -> int:
    key, endpoint_id = require_credentials()
    pins = pins_from_endpoint(fetch_endpoint(endpoint_id, key))
    print(TEMPLATE.format(endpoint_id=endpoint_id, pins=pprint.pformat(pins, width=90)), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
